# Generated by Django 2.1.5 on 2019-02-01 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('avatar_encoding', jsonfield.fields.JSONField(editable=False)),
                ('image_url', models.ImageField(blank=True, upload_to='image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img_url', models.ImageField(null=True, upload_to='recipe/')),
                ('cooking_time', models.CharField(max_length=20, null=True)),
                ('ingredient_table', jsonfield.fields.JSONField(null=True)),
                ('cooking_steps', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
