# Generated by Django 2.1.5 on 2019-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Fridge',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('food_qty', models.IntegerField(max_length=10)),
                ('fridge_img_url', models.CharField(max_length=120)),
                ('fridge_predict_img_url', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('food_category_id', models.ManyToManyField(to='api.Food_Category')),
                ('member_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
    ]
