# Generated by Django 2.1.5 on 2019-02-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_category_member_fridge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_fridge',
            old_name='member_id',
            new_name='member',
        ),
    ]
