# Generated by Django 2.1.5 on 2019-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190215_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_fridge',
            name='food_qty',
            field=models.IntegerField(),
        ),
    ]
