# Generated by Django 2.1.5 on 2019-02-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190215_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_fridge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
    ]
