# Generated by Django 2.1.5 on 2019-02-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190215_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_fridge',
            name='food_category_id',
        ),
        migrations.AddField(
            model_name='member_fridge',
            name='food_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Food_Category'),
            preserve_default=False,
        ),
    ]
