# Generated by Django 2.1.5 on 2019-02-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190215_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_fridge',
            old_name='food_category_id',
            new_name='food_category',
        ),
    ]
