# Generated by Django 2.1.7 on 2019-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190215_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_fridge',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
